### PR TITLE
 Fix #131: Port to Py3.7: handle tstate->exc_info

### LINKED ISSUE #131: Eventlet crashes with Python 3.7
This is a cross reference bug for:

 * https://github.com/eventlet/eventlet/issues/475
 * https://bugs.python.org/issue33996

greenlet only reproducer: [dagpool_test.py](https://bugs.python.org/file47658/dagpool_test.py)

### PR DESCRIPTION
**Pull request by vstinner**
Fix Python 3.7 support: handle also tstate->exc_info, not only
tstate->exc_state.

### CODE REVIEW

**Comment by vstinner** [comment]
@markshannon: Would you mind to review my greenlet fix for Python 3.7, please?

**Comment by vstinner** [comment]
cc @hroncok

File: greenlet.c [hunk 1]
```diff
@@ -153,6 +153,21 @@ static PyObject* ts_empty_dict;
 #define GREENLET_tp_is_gc 0
 #endif /* !GREENLET_USE_GC */
 
+static void green_clear_exc(PyGreenlet *g)
```
Comment (snaury) [inline greenlet.c]: Could you please change it to `PyGreenlet* g`?

File: greenlet.h [hunk 2]
```diff
@@ -25,9 +29,14 @@ typedef struct _greenlet {
 	struct _frame* top_frame;
 	int recursion_depth;
 	PyObject* weakreflist;
+#ifdef GREENLET_USE_EXC_INFO
+	_PyErr_StackItem *exc_info;
```
Comment (snaury) [inline greenlet.h]: Here as well, `_PyErr_StackItem* exc_info`

File: greenlet.c [hunk 3]
```diff
@@ -488,18 +506,20 @@ static int g_switchstack(void)
 		tstate->recursion_depth = target->recursion_depth;
 		tstate->frame = target->top_frame;
 		target->top_frame = NULL;
-#if PY_VERSION_HEX >= 0x030700A3
-		tstate->exc_state.exc_type = target->exc_type;
-		tstate->exc_state.exc_value = target->exc_value;
-		tstate->exc_state.exc_traceback = target->exc_traceback;
+#ifdef GREENLET_USE_EXC_INFO
+		tstate->exc_state = target->exc_state;
+		if (target->exc_info != NULL) {
```
Comment (snaury) [inline greenlet.c]: I think it might be better as a single line: `tstate->exc_info = target->exc_info ? target->exc_info : &tstate->exc_state`.

File: greenlet.c (hunk 1 above)
Comment (vstinner) [reply greenlet.c]: sure, sorry, fixed

File: greenlet.h (hunk 2 above)
Comment (vstinner) [reply greenlet.h]: fixed

File: greenlet.c (hunk 3 above)
Comment (vstinner) [reply greenlet.c]: done

**Comment by vstinner** [comment]
Oh, by the way, I tested manually my PR on Python 3.6 and 3.7 using virtual environments and the commands:

```
python setup.py build
python run-tests.py
python dagpool_test.py
```

where dagpool_test.py comes from: https://bugs.python.org/issue33996

dagpool_test.py is the highly simplified code of eventlet test "tests.dagpool_test.test_propagate_exc".

**Comment by vstinner** [comment]
Ha ha, the 3.7 job of Travis CI failed... on downloading Python!

```
Network availability confirmed.

3.7 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
$ curl -sSf -o python-3.7.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
```

Can someone rebuild this job please?

**Comment by vstinner** [comment]
I just tested the master branch eventlet with the master branch of greenlet: "python -m nose -v tests" no longer crash with this greenlet change. In short, this change fixes https://github.com/eventlet/eventlet/issues/475

**Comment by vstinner** [comment]
I closed/reopened my PR just to re-trigger the Travis CI job. I would like to see a green job for Python 3.7 on Travis CI :-)

**Comment by vstinner** [comment]
Oh. 3.7 still fails with a download error on Travis CI, but it seems like the issue comes from Travis, not greenlet:

```
3.7 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
$ curl -sSf -o python-3.7.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
```

**Comment by hroncok** [comment]
Only alpha or beta on Travis with 3.7-dev

**Comment by vstinner** [comment]
> Only alpha or beta on Travis with 3.7-dev

Let me try with "3.7-dev" in .travis.yml.

It's possible to get 3.7 final with more complex config, but I don't think that it's worth it here. 3.7-dev should be fine until Travis CI officially support 3.7 final.

https://twitter.com/codewithanthony/status/1014168756342251521

```
\o/ @travisci now has `python: 3.7` for `dist: xenial`

 - env: TOXENV=py37
   python: 3.7
   sudo: required
   dist: xenial
```

**Comment by vstinner** [comment]
Say hello to green 3.7 job on Travis CI!

**Comment by snaury** [comment]
> The two Python 3.7 jobs (32 and 64 bits) on Windows (AppVeyor) as also green ;-)

Unfortunately neither Travis nor AppVeyor currently support Python 3.7 release. AppVeyor job actually lies, as it's currently testing and building using Python 2.7 (which is in PATH by default). :-/

**Comment by snaury** [comment]
Thanks for the patch, I will postpone release until AppVeyor releases new images (https://github.com/appveyor/ci/issues/2475)
