### PR TITLE
Resolves #169

### LINKED ISSUE #169: Build broken on Python 3.10
```c
/usr/local/include/python3.10/ceval.h:17:43: note: declared here
     Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    greenlet.c: In function ‘green_dealloc’:
    greenlet.c:1009:19: error: lvalue required as left operand of assignment
       Py_REFCNT(self) = 1;
                       ^
    greenlet.c:1038:7: error: lvalue required as decrement operand
       if (--Py_REFCNT(self) != 0) {
           ^~
    greenlet.c:1042:20: error: lvalue required as left operand of assignment
        Py_REFCNT(self) = refcnt;
```
python/cpython#20429

### PR DESCRIPTION
**Pull request by CyberSaxosTiGER**

### CODE REVIEW

File: greenlet.c [hunk 1]
```diff
@@ -109,6 +109,14 @@ extern PyTypeObject PyGreenlet_Type;
 #define GREENLET_USE_TRACING 1
 #endif
 
+#if PY_VERSION_HEX >= 0x030900A4
+   /* Py_REFCNT and Py_SIZE macros are converted to functions
+   https://bugs.python.org/issue39573 */
+  #define __Py_SET_REFCNT(obj, refcnt) Py_SET_REFCNT(obj, refcnt)
```
[the remark this answers is not in the document]
Comment (CyberSaxosTiGER) [reply greenlet.c]: i updated it

File: greenlet.c [hunk 2]
```diff
@@ -1044,11 +1050,11 @@ static void green_dealloc(PyGreenlet* self)
 		 * it would cause a recursive call.
 		 */
 		assert(Py_REFCNT(self) > 0);
-		if (--Py_REFCNT(self) != 0) {
+		if (--((PyObject*)(self))->ob_refcnt != 0) {
```
Comment (snaury) [inline greenlet.c:1053]: Just noticed, direct field access like this is incorrect. The whole reason for new macros is for this field to eventually go away. This should probably be something like:

```
Py_ssize_t refcnt = Py_REFCNT(self) - 1;
Py_SET_REFCNT(self, refcnt);
if (refcnt != 0) {
    ...
}
```

Comment (CyberSaxosTiGER) [reply greenlet.c]: Yeah, but both ways seemed ugly for me. But i re-updated it according to your request
